nameOverride: ""
fullnameOverride: "examkube"

domain: "jaffleman.tech"
url: "kube.{{ .Values.domain }}"

namespace:
  create: true

replicas:
  fastapi: 4
  postgres: 1

images:
  fastapi: docker.io/jaffleman971/fastapi-image:latest
  postgres: postgres:16-alpine


app:
  host: "0.0.0.0"
  port: 5000
  healthPath: "/docs"


service:
  port: 5000


db:
  host: "db"          
  port: 5432
  name: "storedb"      
  user: "admin"       
  password: "password"


path:
  postgres: "/var/lib/postgresql/data"


resources:
  fastapi:
    requests:
      cpu: "100m"
      memory: "128Mi"
    limits:
      cpu: "500m"
      memory: "512Mi"
  postgres:
    requests:
      cpu: "100m"
      memory: "256Mi"
    limits:
      cpu: "500m"
      memory: "1Gi"


storage:
  class: "local-path"   # k3s par d√©faut
  size: "5Gi"


letsencrypt:
  email: "jaffleman@gmail.com"
  server: "https://acme-v02.api.letsencrypt.org/directory"
  privateKeySecretRef: "letsencrypt-prod"

