apiVersion: v1
kind: ConfigMap
metadata:
  name: app-config
  labels:
    app: fastapi
    {{- include "examkube_chart.labels" . | nindent 4 }}
data:
  APP_HOST: {{ .Values.app.host | quote }}
  APP_PORT: {{ .Values.app.port | quote }}
  APP_HEALTH_PATH: {{ default "/docs" .Values.app.healthPath | quote }}
  DB_HOST: {{ .Values.db.host | quote }}
  DB_PORT: {{ .Values.db.port | quote }}
  DB_NAME: {{ .Values.db.name | quote }}

