
{{- $domain := required "Values.domain est requis (ex: jaffleman.tech)" .Values.domain -}}
{{- $host := printf "examlinux.%s" $domain | lower -}}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "examkube_chart.fullname" . }}
  labels:
    {{- include "examkube_chart.labels" . | nindent 4 }}
  annotations:
    # Sélection du resolver ACME configuré dans Traefik (ex.: "le")
    traefik.ingress.kubernetes.io/router.tls.certresolver: {{ .Values.acme.resolverName | default "le" }}
spec:
  # Classe d’Ingress (remplace l’annotation dépréciée)
  ingressClassName: traefik
  tls:
    - hosts:
        - {{ $host }}
  rules:
    - host: {{ $host }}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: {{ include "examkube_chart.fullname" . }}-fastapi
                # Ton app écoute 5000 (d’après tes manifests) ⇒ ne laisse pas "80"
                port:
                  number: {{ .Values.service.port | default 5000 }}

