
{{- $domain := required "Values.domain est requis (ex: jaffleman.tech)" .Values.domain -}}
{{- $host := printf "examlinux.%s" $domain | lower -}}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "examkube_chart.fullname" . }}
  labels:
    {{- include "examkube_chart.labels" . | nindent 4 }}
  annotations:
    # kubernetes.io/ingress.class: traefik
    # # Traefik ACME resolver "le" (conforme Ã  ton contexte)
    # traefik.ingress.kubernetes.io/router.tls.certresolver: le
spec:
  tls:
    - hosts:
        - {{ $host | lower }}
  rules:
    - host: {{ $host | lower }}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: {{ include "examkube_chart.fullname" . }}-fastapi
                port:
                  number: {{ .Values.service.port | default 80 }}
