
{{- $domain := required "Values.domain est requis (ex: jaffleman.tech)" .Values.domain -}}
{{- $host := printf "kube.%s" $domain | lower -}}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "examkube.fullname" . }}
  labels:
    app.kubernetes.io/name: {{ include "examkube.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
  annotations:
    kubernetes.io/ingress.class: traefik
    # Traefik ACME resolver "le" (conforme Ã  ton contexte)
    traefik.ingress.kubernetes.io/router.tls.certresolver: le
spec:
  tls:
    - hosts:
        - {{ $host }}
  rules:
    - host: {{ $host | lower }}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: {{ include "examkube_chart.fullname" . }}
                port:
                  number: {{ .Values.service.port | default 80 }}
